AWSTemplateFormatVersion: '2010-09-09'
Outputs:
  TestVersionUrl:
    Description: Test Order URL
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/order
Resources:
  OrderFunction:
    Properties:
      CodeUri: s3://lambda-jar-upload/6c1ce6d2c6b6e56529809b42bb535455
      Events:
        PurchaseOrder:
          Properties:
            Method: post
            Path: /order
          Type: Api
      Handler: solid.humank.adapters.OrderHandler::handleRequest
      Runtime: java8
      Timeout: 15
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
