AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  OrderFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: java8
      Handler: solid.humank.domains.Order::handleRequest
      Timeout: 60
      CodeUri: ./target/lambda.jar
