AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  OrderFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: java8
      Handler: solid.humank.adapters.OrderPrxoyHandler::handleRequest
      Timeout: 60
      MemorySize: 256
      CodeUri: ./target/lambda.jar
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaFullAccess
        - CloudWatchEventsFullAccess
      Events:
        PurchaseOrder:
          Type: Api
          Properties:
            Path: /order
            Method: post

Outputs:
  TestOrderUrl:
    Description: "Test Order URL"
    Value:
      'Fn::Sub': "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/order"