AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  AcceptOrderFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: java8
      Handler: solid.humank.port.adapter.OrderAPIGProxyWrapper::handleRequest
      Timeout: 60
      MemorySize: 256
      CodeUri: ./target/lambda.jar
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaFullAccess
        - CloudWatchEventsFullAccess
      Events:
        PurchaseOrder:
          Type: Api
          Properties:
            Path: /order
            Method: post

Outputs:
  AcceptOrderUrl:
    Description: "Accept Order created event URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/order"
  AcceptOrderFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt AcceptOrderFunction.Arn