AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MakeupFunction:
    Properties:
      CodeUri: s3://kim-lambda-store/f019591a69855ecc3c9c862da72cadc6
      Handler: solid.humank.adapters.OrderReceiverAdapter::handleRequest
      MemorySize: 256
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaFullAccess
      - CloudWatchEventsFullAccess
      Runtime: java8
      Timeout: 60
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
